import Head from 'next/head';
import Link from 'next/link';
import { useState } from 'react'
import style from '../styles/Home.module.css'

export default function Home() {

const [name, setName] = useState();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={style.frontpage}>
        <input type="text" placeholder='Enter Your Name' />
        <Link href={'./products'}><button>Proceed</button></Link>

      </div>

    </>
  )
}
